# defining languages dictionary

LANGUAGE_DICT = {
    'afr': 'wesenlikheidsmatriks',
    'amh': 'ቁሳዊነት ማትሪክስ',
    'ara': 'مصفوفة المادية',
    'asm': '',
    'aze': 'əhəmiyyətlilik matrisi',
    'aze_cyrl': '',
    'bel': 'матрыца істотнасці',
    'ben': 'বস্তুগত ম্যাট্রিক্স',
    'bod': '',
    'bos': 'matrica materijalnosti',
    'bre': '',
    'bul': 'матрица на съществеността',
    'cat': 'matriu de materialitat',
    'ceb': 'materyalidad nga matrix',
    'ces': 'matice významnosti',
    'chi_sim': '重要性矩阵',
    'chi_tra': '',
    'chr': '',
    'cos': '',
    'cym': 'matrics perthnasedd',
    'dan': 'væsentlighedsmatrix',
    'deu': 'Materialitätsmatrix',
    'div': '',
    'dzo': '',
    'ell': '',
    'eng': 'materiality matrix',
    'enm': '',
    'epo': '',
    'equ': '',
    'est': 'olulisuse maatriks',
    'eus': 'materialtasun matrizea',
    'fao': '',
    'fas': '',
    'fil': 'materyalidad matrix',
    'fin': 'olennaisuusmatriisi',
    'fra': 'matrice de matérialité',
    'frk': '',
    'frm': '',
    'fry': 'materiality matrix',
    'gla': '',
    'gle': '',
    'glg': '',
    'grc': 'μήτρα ουσιαστικότητας',
    'guj': 'ભૌતિકતા મેટ્રિક્સ',
    'hat': '',
    'heb': '',
    'hin': '',
    'hrv': '',
    'hun': '',
    'hye': '',
    'iku': '',
    'ind': '',
    'isl': '',
    'ita': 'matrice di materialità',
    'jav': '',
    'jpn': 'マテリアリティマトリックス',
    'jpn_vert': '',
    'kat': '',
    'kaz': '',
    'khm': '',
    'kir': '',
    'kmr': '',
    'kor': '중요성 매트릭스',
    'lao': '',
    'lat': '',
    'lav': '',
    'lit': '',
    'ltz': '',
    'mal': 'മെറ്റീരിയൽ മാട്രിക്സ്',
    'mar': '',
    'mkd': '',
    'mlt': '',
    'mon': '',
    'mri': '',
    'msa': '',
    'mya': '',
    'nep': '',
    'nld': '',
    'nor': 'materialitetsmatrise',
    'oci': '',
    'ori': '',
    'osd': '',
    'pan': '',
    'pol': 'macierz istotności',
    'por': 'matriz de materialidade',
    'pus': '',
    'que': '',
    'ron': '',
    'rus': 'матрица существенности',
    'san': '',
    'sin': '',
    'slk': '',
    'slv': '',
    'snd': '',
    'spa': 'matriz de materialidad',
    'sqi': '',
    'srp': '',
    'srp_latn': '',
    'sun': '',
    'swa': '',
    'swe': 'materialitetsmatris',
    'syr': '',
    'tam': '',
    'tat': '',
    'tel': '',
    'tgk': '',
    'tgl': '',
    'tha': '',
    'tir': '',
    'ton': '',
    'tur': 'önemlilik matrisi',
    'uig': '',
    'ukr': '',
    'urd': '',
    'uzb': '',
    'uzb_cyrl': '',
    'vie': '',
    'yid': '',
    'yor': ''
}

# counting languages
if __name__ == '__main__':
    cnt = 0
    for lan in LANGUAGE_DICT.values():
        if lan != '':
            cnt += 1

    print(cnt)